/* Auto-generated by utensor cli */
#include "uTensor.h"
#include "superpoint.hpp"
#include "params_superpoint.hpp"


Superpoint::Superpoint () :
op_MaxPoolOperator_000({ 2, 2 }, { 1, 2, 2, 1 }, VALID)
, op_SumOperator_001()
, op_RsqrtOperator_002()
, op_Conv2dOperator_003({ 1, 1, 1, 1 }, VALID)
, op_MulOperator_004()
, op_ReLUOperator_005()
, op_Conv2dOperator_006({ 1, 1, 1, 1 }, SAME)
{
  // Context::get_default_context()->set_ram_data_allocator(&ram_allocator);
  // Context::get_default_context()->set_metadata_allocator(&metadata_allocator);
  // TODO: moving ROMTensor declarations here
}

void Superpoint::compute()
{
  // update context in case there are multiple models being run
  Context::get_default_context()->set_ram_data_allocator(&ram_allocator);
  Context::get_default_context()->set_metadata_allocator(&metadata_allocator);
  // start rendering local snippets
  Tensor t_conv2dConv2D0 = new RomTensor({ 64, 3, 3, 1 }, flt, data_conv2d_Conv2D_0);


  Tensor t_conv2dBiasAddReadVariableOpresource0 = new RomTensor({ 64 }, flt, data_conv2d_BiasAdd_ReadVariableOp_resource_0);


  Tensor t_re_luRelu__conv2dBiasAdd__conv2d_3Conv2D__conv2dConv2D__conv2dBiasAddReadVariableOpresource0 = new RamTensor({ 1, 120, 90, 64 }, flt);


  op_Conv2dOperator_006
    .set_inputs({
        { ReferenceOperators::Conv2dOperator<float>::in, inputs[input_0].tensor() },
        { ReferenceOperators::Conv2dOperator<float>::filter, t_conv2dConv2D0 },
    })
    .set_outputs({
        { ReferenceOperators::Conv2dOperator<float>::out, t_re_luRelu__conv2dBiasAdd__conv2d_3Conv2D__conv2dConv2D__conv2dBiasAddReadVariableOpresource0}
    })
    .eval();

  t_conv2dConv2D0.free();

  t_conv2dBiasAddReadVariableOpresource0.free();

  Tensor t_0_CONV_2DReLU0 = new RamTensor({ 1, 120, 90, 64 }, flt);


  op_ReLUOperator_005
    .set_inputs({
        { ReferenceOperators::ReLUOperator<float>::in, t_re_luRelu__conv2dBiasAdd__conv2d_3Conv2D__conv2dConv2D__conv2dBiasAddReadVariableOpresource0 },
    })
    .set_outputs({
        { ReferenceOperators::ReLUOperator<float>::out, t_0_CONV_2DReLU0}
    })
    .eval();

  t_re_luRelu__conv2dBiasAdd__conv2d_3Conv2D__conv2dConv2D__conv2dBiasAddReadVariableOpresource0.free();

  Tensor t_conv2d_1Conv2D0 = new RomTensor({ 64, 3, 3, 64 }, flt, data_conv2d_1_Conv2D_0);


  Tensor t_conv2d_1BiasAddReadVariableOpresource0 = new RomTensor({ 64 }, flt, data_conv2d_1_BiasAdd_ReadVariableOp_resource_0);


  Tensor t_re_luRelu_1__conv2d_1BiasAdd__conv2d_3Conv2D__conv2d_1Conv2D__conv2d_1BiasAddReadVariableOpresource0 = new RamTensor({ 1, 120, 90, 64 }, flt);


  op_Conv2dOperator_006
    .set_inputs({
        { ReferenceOperators::Conv2dOperator<float>::in, t_0_CONV_2DReLU0 },
        { ReferenceOperators::Conv2dOperator<float>::filter, t_conv2d_1Conv2D0 },
    })
    .set_outputs({
        { ReferenceOperators::Conv2dOperator<float>::out, t_re_luRelu_1__conv2d_1BiasAdd__conv2d_3Conv2D__conv2d_1Conv2D__conv2d_1BiasAddReadVariableOpresource0}
    })
    .eval();

  t_0_CONV_2DReLU0.free();

  t_conv2d_1BiasAddReadVariableOpresource0.free();

  t_conv2d_1Conv2D0.free();

  Tensor t_1_CONV_2DReLU0 = new RamTensor({ 1, 120, 90, 64 }, flt);


  op_ReLUOperator_005
    .set_inputs({
        { ReferenceOperators::ReLUOperator<float>::in, t_re_luRelu_1__conv2d_1BiasAdd__conv2d_3Conv2D__conv2d_1Conv2D__conv2d_1BiasAddReadVariableOpresource0 },
    })
    .set_outputs({
        { ReferenceOperators::ReLUOperator<float>::out, t_1_CONV_2DReLU0}
    })
    .eval();

  t_re_luRelu_1__conv2d_1BiasAdd__conv2d_3Conv2D__conv2d_1Conv2D__conv2d_1BiasAddReadVariableOpresource0.free();

  Tensor t_max_pooling2dMaxPool0 = new RamTensor({ 1, 60, 45, 64 }, flt);


  op_MaxPoolOperator_000
    .set_inputs({
        { ReferenceOperators::MaxPoolOperator<float>::in, t_1_CONV_2DReLU0 },
    })
    .set_outputs({
        { ReferenceOperators::MaxPoolOperator<float>::out, t_max_pooling2dMaxPool0}
    })
    .eval();

  t_1_CONV_2DReLU0.free();

  Tensor t_conv2d_2Conv2D0 = new RomTensor({ 64, 3, 3, 64 }, flt, data_conv2d_2_Conv2D_0);


  Tensor t_conv2d_2BiasAddReadVariableOpresource0 = new RomTensor({ 64 }, flt, data_conv2d_2_BiasAdd_ReadVariableOp_resource_0);


  Tensor t_re_luRelu_2__conv2d_2BiasAdd__conv2d_3Conv2D__conv2d_2Conv2D__conv2d_2BiasAddReadVariableOpresource0 = new RamTensor({ 1, 60, 45, 64 }, flt);


  op_Conv2dOperator_006
    .set_inputs({
        { ReferenceOperators::Conv2dOperator<float>::in, t_max_pooling2dMaxPool0 },
        { ReferenceOperators::Conv2dOperator<float>::filter, t_conv2d_2Conv2D0 },
    })
    .set_outputs({
        { ReferenceOperators::Conv2dOperator<float>::out, t_re_luRelu_2__conv2d_2BiasAdd__conv2d_3Conv2D__conv2d_2Conv2D__conv2d_2BiasAddReadVariableOpresource0}
    })
    .eval();

  t_max_pooling2dMaxPool0.free();

  t_conv2d_2BiasAddReadVariableOpresource0.free();

  t_conv2d_2Conv2D0.free();

  Tensor t_3_CONV_2DReLU0 = new RamTensor({ 1, 60, 45, 64 }, flt);


  op_ReLUOperator_005
    .set_inputs({
        { ReferenceOperators::ReLUOperator<float>::in, t_re_luRelu_2__conv2d_2BiasAdd__conv2d_3Conv2D__conv2d_2Conv2D__conv2d_2BiasAddReadVariableOpresource0 },
    })
    .set_outputs({
        { ReferenceOperators::ReLUOperator<float>::out, t_3_CONV_2DReLU0}
    })
    .eval();

  t_re_luRelu_2__conv2d_2BiasAdd__conv2d_3Conv2D__conv2d_2Conv2D__conv2d_2BiasAddReadVariableOpresource0.free();

  Tensor t_conv2d_3Conv2D0 = new RomTensor({ 64, 3, 3, 64 }, flt, data_conv2d_3_Conv2D_0);


  Tensor t_conv2d_3BiasAddReadVariableOpresource0 = new RomTensor({ 64 }, flt, data_conv2d_3_BiasAdd_ReadVariableOp_resource_0);


  Tensor t_re_luRelu_3__conv2d_3BiasAdd__conv2d_3Conv2D__conv2d_3BiasAddReadVariableOpresource0 = new RamTensor({ 1, 60, 45, 64 }, flt);


  op_Conv2dOperator_006
    .set_inputs({
        { ReferenceOperators::Conv2dOperator<float>::in, t_3_CONV_2DReLU0 },
        { ReferenceOperators::Conv2dOperator<float>::filter, t_conv2d_3Conv2D0 },
    })
    .set_outputs({
        { ReferenceOperators::Conv2dOperator<float>::out, t_re_luRelu_3__conv2d_3BiasAdd__conv2d_3Conv2D__conv2d_3BiasAddReadVariableOpresource0}
    })
    .eval();

  t_conv2d_3Conv2D0.free();

  t_3_CONV_2DReLU0.free();

  t_conv2d_3BiasAddReadVariableOpresource0.free();

  Tensor t_4_CONV_2DReLU0 = new RamTensor({ 1, 60, 45, 64 }, flt);


  op_ReLUOperator_005
    .set_inputs({
        { ReferenceOperators::ReLUOperator<float>::in, t_re_luRelu_3__conv2d_3BiasAdd__conv2d_3Conv2D__conv2d_3BiasAddReadVariableOpresource0 },
    })
    .set_outputs({
        { ReferenceOperators::ReLUOperator<float>::out, t_4_CONV_2DReLU0}
    })
    .eval();

  t_re_luRelu_3__conv2d_3BiasAdd__conv2d_3Conv2D__conv2d_3BiasAddReadVariableOpresource0.free();

  Tensor t_max_pooling2dMaxPool_10 = new RamTensor({ 1, 30, 22, 64 }, flt);


  op_MaxPoolOperator_000
    .set_inputs({
        { ReferenceOperators::MaxPoolOperator<float>::in, t_4_CONV_2DReLU0 },
    })
    .set_outputs({
        { ReferenceOperators::MaxPoolOperator<float>::out, t_max_pooling2dMaxPool_10}
    })
    .eval();

  t_4_CONV_2DReLU0.free();

  Tensor t_conv2d_4Conv2D0 = new RomTensor({ 128, 3, 3, 64 }, flt, data_conv2d_4_Conv2D_0);


  Tensor t_conv2d_4BiasAddReadVariableOpresource0 = new RomTensor({ 128 }, flt, data_conv2d_4_BiasAdd_ReadVariableOp_resource_0);


  Tensor t_re_luRelu_4__conv2d_4BiasAdd__conv2d_7Conv2D__conv2d_4Conv2D__conv2d_4BiasAddReadVariableOpresource0 = new RamTensor({ 1, 30, 22, 128 }, flt);


  op_Conv2dOperator_006
    .set_inputs({
        { ReferenceOperators::Conv2dOperator<float>::in, t_max_pooling2dMaxPool_10 },
        { ReferenceOperators::Conv2dOperator<float>::filter, t_conv2d_4Conv2D0 },
    })
    .set_outputs({
        { ReferenceOperators::Conv2dOperator<float>::out, t_re_luRelu_4__conv2d_4BiasAdd__conv2d_7Conv2D__conv2d_4Conv2D__conv2d_4BiasAddReadVariableOpresource0}
    })
    .eval();

  t_max_pooling2dMaxPool_10.free();

  t_conv2d_4BiasAddReadVariableOpresource0.free();

  t_conv2d_4Conv2D0.free();

  Tensor t_6_CONV_2DReLU0 = new RamTensor({ 1, 30, 22, 128 }, flt);


  op_ReLUOperator_005
    .set_inputs({
        { ReferenceOperators::ReLUOperator<float>::in, t_re_luRelu_4__conv2d_4BiasAdd__conv2d_7Conv2D__conv2d_4Conv2D__conv2d_4BiasAddReadVariableOpresource0 },
    })
    .set_outputs({
        { ReferenceOperators::ReLUOperator<float>::out, t_6_CONV_2DReLU0}
    })
    .eval();

  t_re_luRelu_4__conv2d_4BiasAdd__conv2d_7Conv2D__conv2d_4Conv2D__conv2d_4BiasAddReadVariableOpresource0.free();

  Tensor t_conv2d_5Conv2D0 = new RomTensor({ 128, 3, 3, 128 }, flt, data_conv2d_5_Conv2D_0);


  Tensor t_conv2d_5BiasAddReadVariableOpresource0 = new RomTensor({ 128 }, flt, data_conv2d_5_BiasAdd_ReadVariableOp_resource_0);


  Tensor t_re_luRelu_5__conv2d_5BiasAdd__conv2d_7Conv2D__conv2d_5Conv2D__conv2d_5BiasAddReadVariableOpresource0 = new RamTensor({ 1, 30, 22, 128 }, flt);


  op_Conv2dOperator_006
    .set_inputs({
        { ReferenceOperators::Conv2dOperator<float>::in, t_6_CONV_2DReLU0 },
        { ReferenceOperators::Conv2dOperator<float>::filter, t_conv2d_5Conv2D0 },
    })
    .set_outputs({
        { ReferenceOperators::Conv2dOperator<float>::out, t_re_luRelu_5__conv2d_5BiasAdd__conv2d_7Conv2D__conv2d_5Conv2D__conv2d_5BiasAddReadVariableOpresource0}
    })
    .eval();

  t_6_CONV_2DReLU0.free();

  t_conv2d_5BiasAddReadVariableOpresource0.free();

  t_conv2d_5Conv2D0.free();

  Tensor t_7_CONV_2DReLU0 = new RamTensor({ 1, 30, 22, 128 }, flt);


  op_ReLUOperator_005
    .set_inputs({
        { ReferenceOperators::ReLUOperator<float>::in, t_re_luRelu_5__conv2d_5BiasAdd__conv2d_7Conv2D__conv2d_5Conv2D__conv2d_5BiasAddReadVariableOpresource0 },
    })
    .set_outputs({
        { ReferenceOperators::ReLUOperator<float>::out, t_7_CONV_2DReLU0}
    })
    .eval();

  t_re_luRelu_5__conv2d_5BiasAdd__conv2d_7Conv2D__conv2d_5Conv2D__conv2d_5BiasAddReadVariableOpresource0.free();

  Tensor t_max_pooling2dMaxPool_20 = new RamTensor({ 1, 15, 11, 128 }, flt);


  op_MaxPoolOperator_000
    .set_inputs({
        { ReferenceOperators::MaxPoolOperator<float>::in, t_7_CONV_2DReLU0 },
    })
    .set_outputs({
        { ReferenceOperators::MaxPoolOperator<float>::out, t_max_pooling2dMaxPool_20}
    })
    .eval();

  t_7_CONV_2DReLU0.free();

  Tensor t_conv2d_6Conv2D0 = new RomTensor({ 128, 3, 3, 128 }, flt, data_conv2d_6_Conv2D_0);


  Tensor t_conv2d_6BiasAddReadVariableOpresource0 = new RomTensor({ 128 }, flt, data_conv2d_6_BiasAdd_ReadVariableOp_resource_0);


  Tensor t_re_luRelu_6__conv2d_6BiasAdd__conv2d_7Conv2D__conv2d_6Conv2D__conv2d_6BiasAddReadVariableOpresource0 = new RamTensor({ 1, 15, 11, 128 }, flt);


  op_Conv2dOperator_006
    .set_inputs({
        { ReferenceOperators::Conv2dOperator<float>::in, t_max_pooling2dMaxPool_20 },
        { ReferenceOperators::Conv2dOperator<float>::filter, t_conv2d_6Conv2D0 },
    })
    .set_outputs({
        { ReferenceOperators::Conv2dOperator<float>::out, t_re_luRelu_6__conv2d_6BiasAdd__conv2d_7Conv2D__conv2d_6Conv2D__conv2d_6BiasAddReadVariableOpresource0}
    })
    .eval();

  t_conv2d_6BiasAddReadVariableOpresource0.free();

  t_max_pooling2dMaxPool_20.free();

  t_conv2d_6Conv2D0.free();

  Tensor t_9_CONV_2DReLU0 = new RamTensor({ 1, 15, 11, 128 }, flt);


  op_ReLUOperator_005
    .set_inputs({
        { ReferenceOperators::ReLUOperator<float>::in, t_re_luRelu_6__conv2d_6BiasAdd__conv2d_7Conv2D__conv2d_6Conv2D__conv2d_6BiasAddReadVariableOpresource0 },
    })
    .set_outputs({
        { ReferenceOperators::ReLUOperator<float>::out, t_9_CONV_2DReLU0}
    })
    .eval();

  t_re_luRelu_6__conv2d_6BiasAdd__conv2d_7Conv2D__conv2d_6Conv2D__conv2d_6BiasAddReadVariableOpresource0.free();

  Tensor t_conv2d_7Conv2D0 = new RomTensor({ 128, 3, 3, 128 }, flt, data_conv2d_7_Conv2D_0);


  Tensor t_conv2d_7BiasAddReadVariableOpresource0 = new RomTensor({ 128 }, flt, data_conv2d_7_BiasAdd_ReadVariableOp_resource_0);


  Tensor t_re_luRelu_7__conv2d_7BiasAdd__conv2d_7Conv2D__conv2d_7BiasAddReadVariableOpresource0 = new RamTensor({ 1, 15, 11, 128 }, flt);


  op_Conv2dOperator_006
    .set_inputs({
        { ReferenceOperators::Conv2dOperator<float>::in, t_9_CONV_2DReLU0 },
        { ReferenceOperators::Conv2dOperator<float>::filter, t_conv2d_7Conv2D0 },
    })
    .set_outputs({
        { ReferenceOperators::Conv2dOperator<float>::out, t_re_luRelu_7__conv2d_7BiasAdd__conv2d_7Conv2D__conv2d_7BiasAddReadVariableOpresource0}
    })
    .eval();

  t_9_CONV_2DReLU0.free();

  t_conv2d_7BiasAddReadVariableOpresource0.free();

  t_conv2d_7Conv2D0.free();

  Tensor t_10_CONV_2DReLU0 = new RamTensor({ 1, 15, 11, 128 }, flt);


  op_ReLUOperator_005
    .set_inputs({
        { ReferenceOperators::ReLUOperator<float>::in, t_re_luRelu_7__conv2d_7BiasAdd__conv2d_7Conv2D__conv2d_7BiasAddReadVariableOpresource0 },
    })
    .set_outputs({
        { ReferenceOperators::ReLUOperator<float>::out, t_10_CONV_2DReLU0}
    })
    .eval();

  t_re_luRelu_7__conv2d_7BiasAdd__conv2d_7Conv2D__conv2d_7BiasAddReadVariableOpresource0.free();

  Tensor t_conv2d_10Conv2D0 = new RomTensor({ 256, 3, 3, 128 }, flt, data_conv2d_10_Conv2D_0);


  Tensor t_conv2d_10BiasAddReadVariableOpresource0 = new RomTensor({ 256 }, flt, data_conv2d_10_BiasAdd_ReadVariableOp_resource_0);


  Tensor t_re_luRelu_8__conv2d_10BiasAdd__conv2d_11Conv2D__conv2d_10Conv2D__conv2d_10BiasAddReadVariableOpresource0 = new RamTensor({ 1, 15, 11, 256 }, flt);


  op_Conv2dOperator_006
    .set_inputs({
        { ReferenceOperators::Conv2dOperator<float>::in, t_10_CONV_2DReLU0 },
        { ReferenceOperators::Conv2dOperator<float>::filter, t_conv2d_10Conv2D0 },
    })
    .set_outputs({
        { ReferenceOperators::Conv2dOperator<float>::out, t_re_luRelu_8__conv2d_10BiasAdd__conv2d_11Conv2D__conv2d_10Conv2D__conv2d_10BiasAddReadVariableOpresource0}
    })
    .eval();

  t_conv2d_10BiasAddReadVariableOpresource0.free();

  t_conv2d_10Conv2D0.free();

  t_10_CONV_2DReLU0.free();

  Tensor t_11_CONV_2DReLU0 = new RamTensor({ 1, 15, 11, 256 }, flt);


  op_ReLUOperator_005
    .set_inputs({
        { ReferenceOperators::ReLUOperator<float>::in, t_re_luRelu_8__conv2d_10BiasAdd__conv2d_11Conv2D__conv2d_10Conv2D__conv2d_10BiasAddReadVariableOpresource0 },
    })
    .set_outputs({
        { ReferenceOperators::ReLUOperator<float>::out, t_11_CONV_2DReLU0}
    })
    .eval();

  t_re_luRelu_8__conv2d_10BiasAdd__conv2d_11Conv2D__conv2d_10Conv2D__conv2d_10BiasAddReadVariableOpresource0.free();

  Tensor t_conv2d_11Conv2D0 = new RomTensor({ 256, 1, 1, 256 }, flt, data_conv2d_11_Conv2D_0);


  Tensor t_conv2d_11BiasAdd__conv2d_11Conv2D__conv2d_11BiasAddReadVariableOpresource0 = new RomTensor({ 256 }, flt, data_conv2d_11_BiasAdd__conv2d_11_Conv2D__conv2d_11_BiasAdd_ReadVariableOp_resource_0);


  Tensor t_conv2d_11BiasAdd__conv2d_11Conv2D__conv2d_11BiasAddReadVariableOpresource10 = new RamTensor({ 1, 15, 11, 256 }, flt);


  op_Conv2dOperator_003
    .set_inputs({
        { ReferenceOperators::Conv2dOperator<float>::in, t_11_CONV_2DReLU0 },
        { ReferenceOperators::Conv2dOperator<float>::filter, t_conv2d_11Conv2D0 },
    })
    .set_outputs({
        { ReferenceOperators::Conv2dOperator<float>::out, t_conv2d_11BiasAdd__conv2d_11Conv2D__conv2d_11BiasAddReadVariableOpresource10}
    })
    .eval();

  t_conv2d_11BiasAdd__conv2d_11Conv2D__conv2d_11BiasAddReadVariableOpresource0.free();

  t_conv2d_11Conv2D0.free();

  t_11_CONV_2DReLU0.free();

  Tensor t_normalizenormmul0 = new RamTensor({ 1, 15, 11, 256 }, flt);


  op_MulOperator_004
    .set_inputs({
        { ReferenceOperators::MulOperator<float>::a, t_conv2d_11BiasAdd__conv2d_11Conv2D__conv2d_11BiasAddReadVariableOpresource10 },
        { ReferenceOperators::MulOperator<float>::b, t_conv2d_11BiasAdd__conv2d_11Conv2D__conv2d_11BiasAddReadVariableOpresource10 },
    })
    .set_outputs({
        { ReferenceOperators::MulOperator<float>::c, t_normalizenormmul0}
    })
    .eval();

  Tensor t_normalizenormSumreduction_indices0 = new RomTensor({ 1 }, i32, data_normalize_norm_Sum_reduction_indices_0);


  Tensor t_normalizenormSum0 = new RamTensor({ 1, 15, 11, 1 }, flt);


  op_SumOperator_001
    .set_inputs({
        { ReferenceOperators::SumOperator<float>::input, t_normalizenormmul0 },
        { ReferenceOperators::SumOperator<float>::axis, t_normalizenormSumreduction_indices0 },
    })
    .set_outputs({
        { ReferenceOperators::SumOperator<float>::output, t_normalizenormSum0}
    })
    .eval();

  t_normalizenormmul0.free();

  t_normalizenormSumreduction_indices0.free();

  Tensor t_normalizetruediv__normalizenormSqrt0 = new RamTensor({ 1, 15, 11, 1 }, flt);


  op_RsqrtOperator_002
    .set_inputs({
        { ReferenceOperators::RsqrtOperator<float>::input, t_normalizenormSum0 },
    })
    .set_outputs({
        { ReferenceOperators::RsqrtOperator<float>::output, t_normalizetruediv__normalizenormSqrt0}
    })
    .eval();

  t_normalizenormSum0.free();

  op_MulOperator_004
    .set_inputs({
        { ReferenceOperators::MulOperator<float>::a, t_conv2d_11BiasAdd__conv2d_11Conv2D__conv2d_11BiasAddReadVariableOpresource10 },
        { ReferenceOperators::MulOperator<float>::b, t_normalizetruediv__normalizenormSqrt0 },
    })
    .set_outputs({
        { ReferenceOperators::MulOperator<float>::c, outputs[output_0].tensor()}
    })
    .eval();

  t_conv2d_11BiasAdd__conv2d_11Conv2D__conv2d_11BiasAddReadVariableOpresource10.free();

  t_normalizetruediv__normalizenormSqrt0.free();
  // end of rendering local snippets
}