/* Auto-generated by utensor cli */
#ifndef __SUPERPOINT_INTERFACE_H
#define __SUPERPOINT_INTERFACE_H
#include "uTensor.h"

using namespace uTensor;

class Superpoint : public ModelInterface<1, 1> {
 public:
  enum input_names : uint8_t { input_0 };
  enum output_names : uint8_t { output_0 };
  Superpoint();

 protected:
  virtual void compute();

 private:
  // Operators
  ReferenceOperators::MulOperator<float> op_MulOperator_000;

  ReferenceOperators::SumOperator<float> op_SumOperator_001;

  ReferenceOperators::ReLUOperator<float> op_ReLUOperator_002;

  ReferenceOperators::RsqrtOperator<float> op_RsqrtOperator_003;

  ReferenceOperators::Conv2dOperator<float> op_Conv2dOperator_004;

  ReferenceOperators::Conv2dOperator<float> op_Conv2dOperator_005;

  ReferenceOperators::MaxPoolOperator<float> op_MaxPoolOperator_006;

  // memory allocators
  localCircularArenaAllocator<256, uint16_t> ram_allocator;
  localCircularArenaAllocator<3072, uint16_t> metadata_allocator;
};

#endif  // __SUPERPOINT_INTERFACE_H