/* Auto-generated by utensor cli */
#ifndef __CIFAR10_CNN_INTERFACE_H
#define __CIFAR10_CNN_INTERFACE_H
#include "uTensor.h"

using namespace uTensor;

class Cifar10Cnn : public ModelInterface<1, 1> 
{
 public:
  enum input_names : uint8_t { input_0 };
  enum output_names : uint8_t { output_0 };
  Cifar10Cnn();
 protected:
  virtual void compute();
 private:
  // Operators
  ReferenceOperators::Conv2dOperator<float> op_Conv2dOperator_000;

  ReferenceOperators::ReLUOperator<float> op_ReLUOperator_001;

  ReferenceOperators::FullyConnectedOperator<float> op_FullyConnectedOperator_002;

  ReferenceOperators::Conv2dOperator<float> op_Conv2dOperator_003;

  ReferenceOperators::AddOperator<float> op_AddOperator_004;

  ReferenceOperators::ReshapeOperator<float> op_ReshapeOperator_005;

  ReferenceOperators::MaxPoolOperator<float> op_MaxPoolOperator_006;

  ReferenceOperators::Conv2dOperator<float> op_Conv2dOperator_007;

  // memory allocators
  localCircularArenaAllocator<218296, uint32_t> ram_allocator;
  localCircularArenaAllocator<2560, uint16_t> metadata_allocator;
};

#endif // __CIFAR10_CNN_INTERFACE_H